package blackjack

func rng(start, end int) []int {
	out := []int{}
	for i := start; i < end+1; i++ {
		out = append(out, i)
	}
	return out
}

type PlayerAction int

const (
	PlayerActionStand PlayerAction = iota
	PlayerActionHit
	PlayerActionDoubleOrStand
	PlayerActionDoubleOrHit
	PlayerActionSplit
)

type RuleV2 struct {
	Actions map[bool]map[int]PlayerAction // map[soft|hard]map[dealerUpcard]Action
}

type RulesMap map[int]RuleV2

// We pre-populate all actions as a hit for player total < 8
var H17Rules = RulesMap{
	2: {map[bool]map[int]PlayerAction{
		false: { // hard
			9:  PlayerActionHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionStand,
			14: PlayerActionStand,
			15: PlayerActionStand,
			16: PlayerActionStand,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionDoubleOrStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}}},
	3: {map[bool]map[int]PlayerAction{
		false: { // hard
			8:  PlayerActionHit,
			9:  PlayerActionDoubleOrHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionStand,
			14: PlayerActionStand,
			15: PlayerActionStand,
			16: PlayerActionStand,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionDoubleOrHit,
			18: PlayerActionDoubleOrStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}}},
	4: {map[bool]map[int]PlayerAction{
		false: { // hard
			8:  PlayerActionHit,
			9:  PlayerActionDoubleOrHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionStand,
			13: PlayerActionStand,
			15: PlayerActionStand,
			14: PlayerActionStand,
			16: PlayerActionStand,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionDoubleOrHit,
			16: PlayerActionDoubleOrHit,
			17: PlayerActionDoubleOrHit,
			18: PlayerActionDoubleOrStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}}},
	5: {map[bool]map[int]PlayerAction{
		false: { // hard
			8:  PlayerActionHit,
			9:  PlayerActionDoubleOrHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionStand,
			13: PlayerActionStand,
			15: PlayerActionStand,
			14: PlayerActionStand,
			16: PlayerActionStand,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionDoubleOrHit,
			13: PlayerActionDoubleOrHit,
			14: PlayerActionDoubleOrHit,
			15: PlayerActionDoubleOrHit,
			16: PlayerActionDoubleOrHit,
			17: PlayerActionDoubleOrHit,
			18: PlayerActionDoubleOrStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}}},
	6: {map[bool]map[int]PlayerAction{
		false: { // hard
			8:  PlayerActionHit,
			9:  PlayerActionDoubleOrHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionStand,
			13: PlayerActionStand,
			15: PlayerActionStand,
			14: PlayerActionStand,
			16: PlayerActionStand,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionDoubleOrHit,
			13: PlayerActionDoubleOrHit,
			14: PlayerActionDoubleOrHit,
			15: PlayerActionDoubleOrHit,
			16: PlayerActionDoubleOrHit,
			17: PlayerActionDoubleOrHit,
			18: PlayerActionDoubleOrStand,
			19: PlayerActionDoubleOrStand,
			20: PlayerActionStand,
		}}},
	7: {map[bool]map[int]PlayerAction{
		false: { // hard
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}}},
	8: {map[bool]map[int]PlayerAction{
		false: { // hard
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}}},
	9: {map[bool]map[int]PlayerAction{
		false: { // hard
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionHit,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}}},
	10: {map[bool]map[int]PlayerAction{
		false: { // hard
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionHit,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}}},
	11: {map[bool]map[int]PlayerAction{
		false: { // hard
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionStand,
			18: PlayerActionStand,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}, true: { // soft
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionHit,
			19: PlayerActionStand,
			20: PlayerActionStand,
		}}}}

var H17Splits = []SplitRule{
	{PlayerCard: 11, DealerUpcard: []int{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}},
	{PlayerCard: 10, DealerUpcard: []int{}},
	{PlayerCard: 9, DealerUpcard: []int{2, 3, 4, 5, 6, 8, 9}},
	{PlayerCard: 8, DealerUpcard: []int{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}},
	{PlayerCard: 7, DealerUpcard: []int{2, 3, 4, 5, 6, 7}},
	{PlayerCard: 6, DealerUpcard: []int{2, 3, 4, 5, 6}},
	{PlayerCard: 5, DealerUpcard: []int{}},
	{PlayerCard: 4, DealerUpcard: []int{5, 6}},
	{PlayerCard: 3, DealerUpcard: []int{2, 3, 4, 5, 6, 7}},
	{PlayerCard: 2, DealerUpcard: []int{2, 3, 4, 5, 6, 7}},
}
