package blackjack

func rng(start, end int) []int {
	out := []int{}
	for i := start; i < end+1; i++ {
		out = append(out, i)
	}
	return out
}

type PlayerAction int

const (
	PlayerActionStand PlayerAction = iota
	PlayerActionHit
	PlayerActionDoubleOrStand
	PlayerActionDoubleOrHit
	PlayerActionSplit
)

type RuleV2 struct {
	Actions map[bool]map[int]PlayerAction // map[soft|hard]map[dealerUpcard]Action
}

var RulesV2 = map[int]RuleV2{ // Anything not listed is implicitly a stand
	2: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionDoubleOrStand,
		}}},
	3: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionDoubleOrHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionDoubleOrHit,
			18: PlayerActionDoubleOrStand,
		}}},
	4: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionDoubleOrHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionDoubleOrHit,
			16: PlayerActionDoubleOrHit,
			17: PlayerActionDoubleOrHit,
			18: PlayerActionDoubleOrStand,
		}}},
	5: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionDoubleOrHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionDoubleOrHit,
			13: PlayerActionDoubleOrHit,
			14: PlayerActionDoubleOrHit,
			15: PlayerActionDoubleOrHit,
			16: PlayerActionDoubleOrHit,
			17: PlayerActionDoubleOrHit,
			18: PlayerActionDoubleOrStand,
		}}},
	6: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionDoubleOrHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionDoubleOrHit,
			13: PlayerActionDoubleOrHit,
			14: PlayerActionDoubleOrHit,
			15: PlayerActionDoubleOrHit,
			16: PlayerActionDoubleOrHit,
			17: PlayerActionDoubleOrHit,
			18: PlayerActionDoubleOrStand,
		}}},
	7: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionStand,
		}}},
	8: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionStand,
		}}},
	9: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionDoubleOrHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionHit,
		}}},
	10: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionHit,
		}}},
	11: {map[bool]map[int]PlayerAction{
		false: { // hard
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionDoubleOrHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
		}, true: { // soft
			2:  PlayerActionHit,
			3:  PlayerActionHit,
			4:  PlayerActionHit,
			5:  PlayerActionHit,
			6:  PlayerActionHit,
			7:  PlayerActionHit,
			8:  PlayerActionHit,
			9:  PlayerActionHit,
			10: PlayerActionHit,
			11: PlayerActionHit,
			12: PlayerActionHit,
			13: PlayerActionHit,
			14: PlayerActionHit,
			15: PlayerActionHit,
			16: PlayerActionHit,
			17: PlayerActionHit,
			18: PlayerActionHit,
		}}}}

var H17Rules = []RuleShorthand{
	{DealerCard: 2, PlayerDoublesOn: []int{10, 11}, PlayerHitsOn: rng(2, 12)},
	{DealerCard: 3, PlayerDoublesOn: []int{9, 10, 11}, PlayerHitsOn: rng(2, 12)},
	{DealerCard: 4, PlayerDoublesOn: []int{9, 10, 11}, PlayerHitsOn: rng(2, 11)},
	{DealerCard: 5, PlayerDoublesOn: []int{9, 10, 11}, PlayerHitsOn: rng(2, 11)},
	{DealerCard: 6, PlayerDoublesOn: []int{9, 10, 11}, PlayerHitsOn: rng(2, 11)},
	{DealerCard: 7, PlayerDoublesOn: []int{10, 11}, PlayerHitsOn: rng(2, 16)},
	{DealerCard: 8, PlayerDoublesOn: []int{10, 11}, PlayerHitsOn: rng(2, 16)},
	{DealerCard: 9, PlayerDoublesOn: []int{10, 11}, PlayerHitsOn: rng(2, 16)},
	{DealerCard: 10, PlayerDoublesOn: []int{11}, PlayerHitsOn: rng(2, 16)},
	{DealerCard: 11, PlayerDoublesOn: []int{11}, PlayerHitsOn: rng(2, 16)},

	{Soft: true, DealerCard: 2, PlayerDoublesOn: []int{18}, PlayerHitsOn: []int{13, 14, 15, 16, 17}},
	{Soft: true, DealerCard: 3, PlayerDoublesOn: []int{18, 17}, PlayerHitsOn: []int{13, 14, 15, 16}},
	{Soft: true, DealerCard: 4, PlayerDoublesOn: []int{18, 17, 16, 15}, PlayerHitsOn: []int{13, 14}},
	{Soft: true, DealerCard: 5, PlayerDoublesOn: []int{18, 17, 16, 15, 14, 13}, PlayerHitsOn: []int{}},
	{Soft: true, DealerCard: 6, PlayerDoublesOn: []int{19, 18, 17, 16, 15, 14, 13}, PlayerHitsOn: []int{}},
	{Soft: true, DealerCard: 7, PlayerHitsOn: []int{17, 16, 15, 14, 13}},
	{Soft: true, DealerCard: 8, PlayerHitsOn: []int{17, 16, 15, 14, 13}},
	{Soft: true, DealerCard: 9, PlayerHitsOn: []int{18, 17, 16, 15, 14, 13}},
	{Soft: true, DealerCard: 10, PlayerHitsOn: []int{18, 17, 16, 15, 14, 13}},
	{Soft: true, DealerCard: 11, PlayerHitsOn: []int{18, 17, 16, 15, 14, 13}},
}

var H17Splits = []SplitRule{
	{PlayerCard: 11, DealerUpcard: []int{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}},
	{PlayerCard: 10, DealerUpcard: []int{}},
	{PlayerCard: 9, DealerUpcard: []int{2, 3, 4, 5, 6, 8, 9}},
	{PlayerCard: 8, DealerUpcard: []int{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}},
	{PlayerCard: 7, DealerUpcard: []int{2, 3, 4, 5, 6, 7}},
	{PlayerCard: 6, DealerUpcard: []int{2, 3, 4, 5, 6}},
	{PlayerCard: 5, DealerUpcard: []int{}},
	{PlayerCard: 4, DealerUpcard: []int{5, 6}},
	{PlayerCard: 3, DealerUpcard: []int{2, 3, 4, 5, 6, 7}},
	{PlayerCard: 2, DealerUpcard: []int{2, 3, 4, 5, 6, 7}},
}
